### ISSUE TITLE
Fix manual path

### ISSUE THREAD

**Issue by qsuscs** [neomutt/gentoo-neomutt#10]
`/usr/share/doc/neomutt-20170609/manual.txt: No such file or directory`
It gets compressed on install.  Needs check whether the compression and method (bz2, gz, …) is deterministic and patch the path and the pager.

**Comment by bazz1tv** [comment]
Dear neomutt contributor,

I also notice this issue.

Although unsuitable, here is a Temporary work-around
```
macro generic <F1> \                                                      
"<enter-command>unset wait_key<enter>\                                    
<shell-escape>less /usr/share/doc/neomutt*/manual.txt.bz2<enter>\         
<enter-command>set wait_key<enter>" \                                     
'show Mutt documentation' 
```
