### ISSUE TITLE
Fix Maildir location

### ISSUE THREAD

**Issue by qsuscs** [neomutt/gentoo-neomutt#12]
The Gentoo default seems to be `$HOME/.maildir` (citation needed).  It might, however, break other people's workflow, so I suppose we should post a notification on the next update.

**Comment by r3lgar** [comment]
>The Gentoo default seems to be `$HOME/.maildir`

Where you find it?

>It might, however, break other people's workflow

Of course it might, but I have never seen people who use defaults.

**Comment by qsuscs** [comment]
https://wiki.gentoo.org/wiki/Postfix#maildir for example.  Not an authoritative source, of course, I'm still searching for such.

**Comment by r3lgar** [comment]
>Not an authoritative source

Why not? It's a distro's wiki, it's authoritative for its users. But I think that it doesn't matter for desktop users.

**Comment by floand** [comment]
The default user mailbox location for maildir format on Gentoo Linux is `$HOME/.maildir`. Also a USE-flag ‘maildir’ [1]:

> maildir - Add support for maildir (~/.maildir) style mail spools

exists which currently is or can be used by/with:

- app-shells/zsh
- mail-mta/exim
- net-mail/dovecot
- net-mail/popa3d
- net-mail/tpop3d


Resources:

[1] <https://packages.gentoo.org/useflags/search?q=maildir>
[2] <https://wiki.gentoo.org/wiki/GLEP:32>
[3] <https://bugs.gentoo.org/show_bug.cgi?id=52076>
