### ISSUE TITLE
/usr/bin/install: cannot stat 'OPS*': No such file or directory

### ISSUE THREAD

**Issue by gallatin1988** [neomutt/gentoo-neomutt#13]
[neomutt_build_log.zip](https://github.com/neomutt/gentoo-neomutt/files/1284701/neomutt_build_log.zip)
ERROR: mail-client/neomutt-20170907::neomutt_gentoo failed (install phase): dodoc failed.
See below for build log excerpt:

 /usr/lib/portage/python3.6/ebuild-helpers/xattr/install -c -m 644 ./neomutt-syntax.vim /var/tmp/portage/mail-client/neomutt-20170907/image//usr/share/doc/neomutt-20170907
make[3]: Leaving directory '/var/tmp/portage/mail-client/neomutt-20170907/work/neomutt-neomutt-20170907/doc'
make[2]: Leaving directory '/var/tmp/portage/mail-client/neomutt-20170907/work/neomutt-neomutt-20170907/doc'
Making install in po
make[2]: Entering directory '/var/tmp/portage/mail-client/neomutt-20170907/work/neomutt-neomutt-20170907/po'
/bin/mkdir -p /var/tmp/portage/mail-client/neomutt-20170907/image//usr/share
if test "mutt" = "gettext-tools"; then \
  /bin/mkdir -p /var/tmp/portage/mail-client/neomutt-20170907/image//usr/share/gettext/po; \
  for file in Makefile.in.in remove-potcdate.sin quot.sed boldquot.sed en@quot.header en@boldquot.header insert-header.sin Rules-quot   Makevars.template; do \
    /usr/lib/portage/python3.6/ebuild-helpers/xattr/install -c -m 644 ./$file \
		    /var/tmp/portage/mail-client/neomutt-20170907/image//usr/share/gettext/po/$file; \
  done; \
  for file in Makevars; do \
    rm -f /var/tmp/portage/mail-client/neomutt-20170907/image//usr/share/gettext/po/$file; \
  done; \
else \
  : ; \
fi
make[2]: Leaving directory '/var/tmp/portage/mail-client/neomutt-20170907/work/neomutt-neomutt-20170907/po'
make[2]: Entering directory '/var/tmp/portage/mail-client/neomutt-20170907/work/neomutt-neomutt-20170907'
make[3]: Entering directory '/var/tmp/portage/mail-client/neomutt-20170907/work/neomutt-neomutt-20170907'
/bin/mkdir -p /var/tmp/portage/mail-client/neomutt-20170907/image//etc/neomutt
 /bin/mkdir -p '/var/tmp/portage/mail-client/neomutt-20170907/image//usr/bin'
 /bin/mkdir -p '/var/tmp/portage/mail-client/neomutt-20170907/image//usr/bin'
/usr/lib/portage/python3.6/ebuild-helpers/xattr/install -c -m 644 ./mime.types /var/tmp/portage/mail-client/neomutt-20170907/image//etc/neomutt/mime.types.dist
  /usr/lib/portage/python3.6/ebuild-helpers/xattr/install -c mutt pgpring pgpewrap '/var/tmp/portage/mail-client/neomutt-20170907/image//usr/bin'
 /usr/lib/portage/python3.6/ebuild-helpers/xattr/install -c ./contrib/smime_keys '/var/tmp/portage/mail-client/neomutt-20170907/image//usr/bin'
if [ ! -f /var/tmp/portage/mail-client/neomutt-20170907/image//etc/neomutt/mime.types ]; then \
	/usr/lib/portage/python3.6/ebuild-helpers/xattr/install -c -m 644 ./mime.types /var/tmp/portage/mail-client/neomutt-20170907/image//etc/neomutt; \
fi
make[3]: Leaving directory '/var/tmp/portage/mail-client/neomutt-20170907/work/neomutt-neomutt-20170907'
make[2]: Leaving directory '/var/tmp/portage/mail-client/neomutt-20170907/work/neomutt-neomutt-20170907'
make[1]: Leaving directory '/var/tmp/portage/mail-client/neomutt-20170907/work/neomutt-neomutt-20170907'
mv: cannot stat '/var/tmp/portage/mail-client/neomutt-20170907/image//usr/share/locale/*/LC_MESSAGES/mutt.mo': No such file or directory
/usr/bin/install: cannot stat 'OPS*': No such file or directory
!!! dodoc: OPS* does not exist
 * ERROR: mail-client/neomutt-20170907::neomutt_gentoo failed (install phase):
 *   dodoc failed
 * 
 * If you need support, post the output of `emerge --info '=mail-client/neomutt-20170907::neomutt_gentoo'`,
 * the complete build log and the output of `emerge -pqv '=mail-client/neomutt-20170907::neomutt_gentoo'`.
 * The complete build log is located at '/var/log/portage/mail-client:neomutt-20170907:20170907-031555.log'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/mail-client/neomutt-20170907/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/mail-client/neomutt-20170907/temp/environment'.
 * Working directory: '/var/tmp/portage/mail-client/neomutt-20170907/work/neomutt-neomutt-20170907'
 * S: '/var/tmp/portage/mail-client/neomutt-20170907/work/neomutt-neomutt-20170907'
 * QA Notice: file does not exist:
 * 
 * 	dodoc: OPS* does not exist
 * QA Notice: Unrecognized configure options:
 * 
 * 	--enable-nfs-fix
 * 	--with-exec-shell
 * 	--enable-nfs-fix
 * 	--with-exec-shell

**Comment by flatcap** [comment]
Argh, sorry about that.
The OPS files weren't docs and have now gone away.
I've update the build files.
Please can you give it another go.

**Comment by gallatin1988** [comment]
Neomutt successfully emerged.
Thanks for the quick response.
