### ISSUE TITLE
no mutt.mo or mutt_dotlock files

### ISSUE THREAD

**Issue by gallatin1988** [neomutt/gentoo-neomutt#4]
ebuild fails withs following message:

mv: cannot stat '/var/tmp/portage/mail-client/neomutt-20170602/image//usr/share/locale/*/LC_MESSAGES/mutt.mo': No such file or directory
chown: cannot access '/var/tmp/portage/mail-client/neomutt-20170602/image//usr/bin/mutt_dotlock': No such file or directory
 * ERROR: mail-client/neomutt-20170602::neomutt_gentoo failed (install phase):
 *   fowners failed

Not sure how to proceed. Any advice?

**Comment by flatcap** [comment]
We'd made some changes, recently to streamline the build.
By default, `mutt_dotlock` isn't build any more.  I can see how that would break your install.

As for the messages, I'm not sure.  They may be a side-effect of the unused options.

I've pushed some changes into a branch [issue/4].
Please can you give it a test.

**Comment by qsuscs** [comment]
I’ve tested it:  `PATCHES` was forgotten to remove in `dodoc`, everything else looks okay.
So:
```patch
diff --git a/mail-client/neomutt/neomutt-20170602.ebuild b/mail-client/neomutt/neomutt-20170602.ebuild
index b81a294..1c9cb1c 100644
--- a/mail-client/neomutt/neomutt-20170602.ebuild
+++ b/mail-client/neomutt/neomutt-20170602.ebuild
@@ -163,5 +163,5 @@ src_install() {
                mv "${f}" "${f%/*}/mutt.mo"
        done
 
-       dodoc COPYRIGHT ChangeLog OPS* PATCHES README*
+       dodoc COPYRIGHT ChangeLog OPS* README*
 }
```

**Comment by flatcap** [comment]
I've pushed the changes which should fix things.
If you're still having problems, re-open the issue and we'll keep looking.

**Comment by gallatin1988** [comment]
Thanks.
I was able to successfully emerge neomutt this morning (06/04/17).
